variables:
  PLUGIN_NAME: 'titlePageForPreprint'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops/unit_tests.yml'
      - 'templates/groups/ops/cypress_tests.yml'

.unit_test_template:
  before_script:
    - apt update && apt install poppler-utils imagemagick php8.2-imagick xmlstarlet -yqq
    - composer install
    - sed -i 's/stealth="true"\/>/stealth="true"\/> -->/' /etc/ImageMagick-6/policy.xml
    - xmlstarlet edit --inplace -u "policymap/policy[@pattern='PDF']/@rights" -v 'read|write' /etc/ImageMagick-6/policy.xml
    - wget https://github.com/coherentgraphics/cpdf-binaries/blob/master/Linux-Intel-64bit/cpdf?raw=true -O /usr/local/bin/cpdf
    - chmod +x /usr/local/bin/cpdf

.integration_tests_template:
  before_script:
    - apt update && apt install poppler-utils -yqq
    - composer install
    - wget https://github.com/coherentgraphics/cpdf-binaries/blob/master/Linux-Intel-64bit/cpdf?raw=true -O /usr/local/bin/cpdf
    - chmod +x /usr/local/bin/cpdf