<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'composition' => '/Composition.inc.php',
                'titlepage' => '/TitlePage.inc.php',
                'pdf' => '/Pdf.inc.php',
                'submissionpress' => '/SubmissionPress.inc.php',
                'submissionpressfortests' => '/SubmissionPressForTests.inc.php',
                'submissionpresspkp' => '/SubmissionPressPKP.inc.php',
                'submissionmodel' => '/SubmissionModel.inc.php',
                'translator' => '/Translator.inc.php',
                'translatorfortests' => '/TranslatorForTests.inc.php',
                'translatorPKP' => '/TranslatorPKP.inc.php',
                'submissionfilesettingsdao' => '/SubmissionFileSettingsDAO.inc.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
