<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'folhaderosto' => '/FolhaDeRosto.inc.php',
                'pdf' => '/Pdf.inc.php',
                'prensadesubmissoes' => '/PrensaDeSubmissoes.inc.php',
                'submissao' => '/Submissao.inc.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
